create table if not exists cards (
    card_id text primary key,
    display_name text not null,
    description text not null default '',
    starts_unlocked boolean not null default false,
    biome_id text not null,
    floor_color_hex text not null,
    wall_color_hex text not null,
    segment_width integer not null check (segment_width >= 5),
    segment_height integer not null check (segment_height >= 5),
    entry_x integer not null,
    exit_x integer not null,
    obstacle_chance real not null check (obstacle_chance >= 0 and obstacle_chance <= 1),
    enemy_chance real not null check (enemy_chance >= 0 and enemy_chance <= 1),
    enemy_ids jsonb not null default '[]'::jsonb,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists player_progress (
    player_id text primary key,
    unlocked_card_ids jsonb not null default '[]'::jsonb,
    completed_runs integer not null default 0,
    failed_runs integer not null default 0,
    total_runs_started integer not null default 0,
    total_cards_unlocked integer not null default 0,
    updated_at timestamptz not null default now()
);

insert into cards (
    card_id,
    display_name,
    description,
    starts_unlocked,
    biome_id,
    floor_color_hex,
    wall_color_hex,
    segment_width,
    segment_height,
    entry_x,
    exit_x,
    obstacle_chance,
    enemy_chance,
    enemy_ids,
    sort_order
)
values
    (
        'verdant_path',
        'Sender Verdant',
        'Boscos oberts amb pocs obstacles i amenaces moderades.',
        true,
        'forest',
        '#7EAD66',
        '#385C36',
        16,
        10,
        1,
        14,
        0.10,
        0.12,
        '["grunt"]'::jsonb,
        10
    ),
    (
        'ashen_corridor',
        'Corredor Cendros',
        'Ruines estretes amb molts murs i emboscades frequents.',
        true,
        'ruins',
        '#938E85',
        '#443E3B',
        17,
        10,
        1,
        15,
        0.18,
        0.18,
        '["grunt"]'::jsonb,
        20
    ),
    (
        'moonlit_bog',
        'Aiguamoll Lunar',
        'Bioma dens amb camins irregulars i enemics puntuals.',
        true,
        'swamp',
        '#628371',
        '#274237',
        16,
        11,
        1,
        14,
        0.16,
        0.14,
        '["grunt"]'::jsonb,
        30
    ),
    (
        'saffron_dunes',
        'Dunes Safra',
        'Zona mes oberta on el perill arriba en onades disperses.',
        false,
        'desert',
        '#D7B870',
        '#855C31',
        18,
        10,
        1,
        16,
        0.08,
        0.20,
        '["grunt"]'::jsonb,
        40
    ),
    (
        'ivory_citadel',
        'Ciutadella d''Ivori',
        'Segment llarg i perillos on l''heroi ha de forcar rutes alternatives.',
        false,
        'citadel',
        '#C7CBCF',
        '#4F5462',
        19,
        11,
        1,
        17,
        0.20,
        0.16,
        '["grunt"]'::jsonb,
        50
    ),
    (
        'ember_depths',
        'Fondaries Brasa',
        'Coves calentes amb passadissos trencats i pressio constant.',
        false,
        'cavern',
        '#AF6746',
        '#572A1F',
        17,
        11,
        1,
        15,
        0.22,
        0.22,
        '["grunt"]'::jsonb,
        60
    )
on conflict (card_id) do update
set
    display_name = excluded.display_name,
    description = excluded.description,
    starts_unlocked = excluded.starts_unlocked,
    biome_id = excluded.biome_id,
    floor_color_hex = excluded.floor_color_hex,
    wall_color_hex = excluded.wall_color_hex,
    segment_width = excluded.segment_width,
    segment_height = excluded.segment_height,
    entry_x = excluded.entry_x,
    exit_x = excluded.exit_x,
    obstacle_chance = excluded.obstacle_chance,
    enemy_chance = excluded.enemy_chance,
    enemy_ids = excluded.enemy_ids,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();
